apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: workshop-404
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
