kind: Pod
apiVersion: v1
metadata:
  name: my-persistent-pod
  namespace: workshop-404
spec:
  containers:
    - name: nginx
      image: nginx:1.15.8
      volumeMounts:
      - mountPath: "/var/www/html"
        name: my-volume-name
  volumes:
    - name: my-volume-name
      persistentVolumeClaim:
        claimName: my-pvc
